name: Run
on: push

jobs:
  make-pl-crash:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install the project
        run: poetry install

      - name: Run
        run: |
          poetry run python main.py
